spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/video_db

eureka:
  client:
    serviceUrl:
      defaultZone: http://service-discovery:8761/eureka/
  instance:
    prefer-ip-address: true