rootProject.name = 'video-streaming-platform'

include 'api-gateway'
include 'auth-service'
include 'user-service'
include 'video-service'
include 'upload-service'
include 'transcoding-service'
include 'streaming-service'
include 'recommendation-service'
include 'notification-service'
include 'search-service'
include 'analytics-service'
include 'service-discovery'
