plugins {
    id 'org.springframework.boot'
    id 'io.spring.dependency-management'
    id 'java'
}

group = 'com.videostreaming'
version = '1.0.0'

repositories {
    mavenCentral()
}

dependencies {

    implementation 'org.springframework.cloud:spring-cloud-starter-netflix-eureka-server'

    testImplementation 'org.springframework.boot:spring-boot-starter-test'
}
tasks.named('test') {
    useJUnitPlatform()
}

bootJar {
    archiveFileName = 'app.jar'
}

jar {
    enabled = false
}
