spring:
  application:
    name: upload-service
  servlet:
    multipart:
      max-file-size: 5GB
      max-request-size: 5GB
  datasource:
    username: ather
    password: jam18EE-t
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
#  rabbitmq:
#    host: localhost
#    port: 5672
#    username: guest
#    password: guest

server:
  port: 8084
  tomcat:
    max-http-post-size: 5368709120
    max-swallow-size: 5368709120

aws:
  s3:
    bucket: video-uploads
    region: us-east-1

minio:
  access-key: minioadmin
  secret-key: minioadmin
  bucket-name: videos
  default-expiry-hours: 24

#spring:
#  datasource:
#    url: jdbc:h2:mem:upload_db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
#    driverClassName: org.h2.Driver
#    username: sa
#    password:
#  jpa:
#    hibernate:
#      ddl-auto: update
#    properties:
#      hibernate:
#        format_sql: true
#  h2:
#    console:
#      enabled: true

